# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [166,235]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [288,402]
                    mode: outbound
        large:
            quality: 75
            filters:
                thumbnail:
                    size: [580,800]
                    mode: outbound